### ISSUE TITLE
Can Node#getCommonAncestor return null?

### ISSUE THREAD

**Issue by edg2s** [TRowbotham/PHPJS#12]
The documentation claims it can:
> Gets the bottom most common ancestor of two nodes, if any. If null is returned, the two nodes do not have a
> common ancestor.

By the type hinting returns `self`, not `?self`.

Currently no callers in tests are using different-document nodes, or you would get a runtime error from the typehint.

**Comment by TRowbotham** [comment]
Thanks for pointing this out. Yes, it can return null if the nodes are in different documents or if both of the nodes have the same owning document and at least one of them is not in the tree.
